apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::910369256577:role/eksctl-eksctl-demo-nodegroup-ng-8-NodeInstanceRole-24LG6AS4LGV0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::910369256577:role/UdacityFlaskDeployCBKubectlRole
      username: build

kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-17T13:14:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1705"
  uid: 4a5eb906-2827-4dd6-8f2a-713dd4f3f3a8
